#include "asset_loader.hpp"

void AssetLoader::loadTextures()
{
    // Textures
    this->resourceManager->addTexture(
        "placeholder_texture",
        "src/assets/textures/placeholder.png"
    );
    this->resourceManager->addTexture(
        "bricks_texture",
        "src/assets/textures/bricks.png"
    );
    this->resourceManager->addTexture(
        "bricks_hit_texture",
        "src/assets/textures/bricks_hit.png"
    );
    this->resourceManager->addTexture(
        "bricks_damaged_texture",
        "src/assets/textures/bricks_damaged.png"
    );
    this->resourceManager->addTexture(
        "bricks_destroyed_texture",
        "src/assets/textures/bricks_destroyed.png"
    );
    this->resourceManager->addTexture(
        "bullet_texture",
        "src/assets/textures/bullet.png"
    );
    this->resourceManager->addTexture(
        "character_hit_texture",
        "src/assets/textures/characters/character_hit.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_texture",
        "src/assets/textures/boards_horizontal.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_hit_texture",
        "src/assets/textures/boards_horizontal_hit.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_damaged_texture",
        "src/assets/textures/boards_horizontal_damaged.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_destroyed_texture",
        "src/assets/textures/boards_horizontal_destroyed.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_texture",
        "src/assets/textures/boards_vertical.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_hit_texture",
        "src/assets/textures/boards_vertical_hit.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_damaged_texture",
        "src/assets/textures/boards_vertical_damaged.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_destroyed_texture",
        "src/assets/textures/boards_vertical_destroyed.png"
    );
    this->resourceManager->addTexture(
        "explosion_texture",
        "src/assets/textures/explosion.png"
    );
    this->resourceManager->addTexture(
        "grenade_on_texture",
        "src/assets/textures/grenade_on.png"
    );
    this->resourceManager->addTexture(
        "grenade_off_texture",
        "src/assets/textures/grenade_off.png"
    );
    this->resourceManager->addTexture(
        "tree_texture",
        "src/assets/textures/tree.png"
    );
    this->resourceManager->addTexture(
        "tree_hit_texture",
        "src/assets/textures/tree_hit.png"
    );
    this->resourceManager->addTexture(
        "tree_destroyed_texture",
        "src/assets/textures/tree_destroyed.png"
    );
    this->resourceManager->addTexture(
        "melee_texture",
        "src/assets/textures/melee.png"
    );
    this->resourceManager->addTexture(
        "debug_point_texture",
        "src/assets/textures/debug_point.png"
    );

    // Player textures
    this->resourceManager->addTexture(
        "player_north_texture",
        "src/assets/textures/characters/player_north.png"
    );
    this->resourceManager->addTexture(
        "player_south_texture",
        "src/assets/textures/characters/player_south.png"
    );
    this->resourceManager->addTexture(
        "player_east_texture",
        "src/assets/textures/characters/player_east.png"
    );
    this->resourceManager->addTexture(
        "player_west_texture",
        "src/assets/textures/characters/player_west.png"
    );
    this->resourceManager->addTexture(
        "player_dead1_texture",
        "src/assets/textures/characters/player_dead1.png"
    );
    this->resourceManager->addTexture(
        "player_dead2_texture",
        "src/assets/textures/characters/player_dead2.png"
    );

    // Enemy textures
    this->resourceManager->addTexture(
        "enemy_north_texture",
        "src/assets/textures/characters/enemy_north.png"
    );
    this->resourceManager->addTexture(
        "enemy_south_texture",
        "src/assets/textures/characters/enemy_south.png"
    );
    this->resourceManager->addTexture(
        "enemy_east_texture",
        "src/assets/textures/characters/enemy_east.png"
    );
    this->resourceManager->addTexture(
        "enemy_west_texture",
        "src/assets/textures/characters/enemy_west.png"
    );
    this->resourceManager->addTexture(
        "enemy_dead1_texture",
        "src/assets/textures/characters/enemy_dead1.png"
    );
    this->resourceManager->addTexture(
        "enemy_dead2_texture",
        "src/assets/textures/characters/enemy_dead2.png"
    );

    // Comrade textures
    this->resourceManager->addTexture(
        "comrade_north_texture",
        "src/assets/textures/characters/comrade_north.png"
    );
    this->resourceManager->addTexture(
        "comrade_south_texture",
        "src/assets/textures/characters/comrade_south.png"
    );
    this->resourceManager->addTexture(
        "comrade_east_texture",
        "src/assets/textures/characters/comrade_east.png"
    );
    this->resourceManager->addTexture(
        "comrade_west_texture",
        "src/assets/textures/characters/comrade_west.png"
    );
    this->resourceManager->addTexture(
        "comrade_dead1_texture",
        "src/assets/textures/characters/comrade_dead1.png"
    );
    this->resourceManager->addTexture(
        "comrade_dead2_texture",
        "src/assets/textures/characters/comrade_dead2.png"
    );
}