#include "asset_loader.hpp"

void AssetLoader::loadSounds()
{
    // Sounds
    this->resourceManager->addSound(
        "gunshot1_sound",
        "src/assets/sounds/gunshot1.wav"
    );
    this->resourceManager->addSound(
        "death_cry1_sound",
        "src/assets/sounds/death_cry1.wav"
    );
    this->resourceManager->addSound(
        "death_cry2_sound",
        "src/assets/sounds/death_cry2.wav"
    );
        this->resourceManager->addSound(
        "death_cry3_sound",
        "src/assets/sounds/death_cry3.wav"
    );
    this->resourceManager->addSound(
        "death_cry4_sound",
        "src/assets/sounds/death_cry4.wav"
    );
    this->resourceManager->addSound(
        "explosion1_sound",
        "src/assets/sounds/explosion1.wav"
    );
    this->resourceManager->addSound(
        "explosion2_sound",
        "src/assets/sounds/explosion2.wav"
    );
    this->resourceManager->addSound(
        "explosion3_sound",
        "src/assets/sounds/explosion3.wav"
    );
    this->resourceManager->addSound(
        "grenade_beep_sound",
        "src/assets/sounds/grenade_beep.wav"
    );
    this->resourceManager->addSound(
        "wilhelm_scream1_sound",
        "src/assets/sounds/wilhelm_scream1.wav"
    );
    this->resourceManager->addSound(
        "wilhelm_scream2_sound",
        "src/assets/sounds/wilhelm_scream2.wav"
    );
    this->resourceManager->addSound(
        "wilhelm_scream3_sound",
        "src/assets/sounds/wilhelm_scream3.wav"
    );
    this->resourceManager->addSound(
        "wilhelm_scream4_sound",
        "src/assets/sounds/wilhelm_scream4.wav"
    );
}