#include "asset_loader.hpp"

void AssetLoader::loadMaterials()
{
    // Materials
    this->resourceManager->addMaterial(
        "placeholder_material",
        "sprite_shader",
        "placeholder_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_material",
        "sprite_shader",
        "bricks_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_hit_material",
        "sprite_shader",
        "bricks_hit_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_damaged_material",
        "sprite_shader",
        "bricks_damaged_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_destroyed_material",
        "sprite_shader",
        "bricks_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "bullet_material",
        "sprite_shader",
        "bullet_texture"
    );
    this->resourceManager->addMaterial(
        "character_hit_material",
        "sprite_shader",
        "character_hit_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_material",
        "sprite_shader",
        "boards_horizontal_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_hit_material",
        "sprite_shader",
        "boards_horizontal_hit_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_damaged_material",
        "sprite_shader",
        "boards_horizontal_damaged_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_destroyed_material",
        "sprite_shader",
        "boards_horizontal_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_material",
        "sprite_shader",
        "boards_vertical_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_hit_material",
        "sprite_shader",
        "boards_vertical_hit_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_damaged_material",
        "sprite_shader",
        "boards_vertical_damaged_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_destroyed_material",
        "sprite_shader",
        "boards_vertical_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "explosion_material",
        "sprite_shader",
        "explosion_texture"
    );
    this->resourceManager->addMaterial(
        "grenade_on_material",
        "sprite_shader",
        "grenade_on_texture"
    );
    this->resourceManager->addMaterial(
        "grenade_off_material",
        "sprite_shader",
        "grenade_off_texture"
    );
    this->resourceManager->addMaterial(
        "tree_material",
        "sprite_shader",
        "tree_texture"
    );
    this->resourceManager->addMaterial(
        "tree_hit_material",
        "sprite_shader",
        "tree_hit_texture"
    );
    this->resourceManager->addMaterial(
        "tree_destroyed_material",
        "sprite_shader",
        "tree_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "melee_material",
        "sprite_shader",
        "melee_texture"
    );
    this->resourceManager->addMaterial(
        "debug_point_material",
        "sprite_shader",
        "debug_point_texture"
    );

    // Player material
    this->resourceManager->addMaterial(
        "player_north_material",
        "sprite_shader",
        "player_north_texture"
    );
    this->resourceManager->addMaterial(
        "player_south_material",
        "sprite_shader",
        "player_south_texture"
    );
    this->resourceManager->addMaterial(
        "player_east_material",
        "sprite_shader",
        "player_east_texture"
    );
    this->resourceManager->addMaterial(
        "player_west_material",
        "sprite_shader",
        "player_west_texture"
    );
    this->resourceManager->addMaterial(
        "player_dead1_material",
        "sprite_shader",
        "player_dead1_texture"
    );
    this->resourceManager->addMaterial(
        "player_dead2_material",
        "sprite_shader",
        "player_dead2_texture"
    );

    // Enemy material
    this->resourceManager->addMaterial(
        "enemy_north_material",
        "sprite_shader",
        "enemy_north_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_south_material",
        "sprite_shader",
        "enemy_south_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_east_material",
        "sprite_shader",
        "enemy_east_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_west_material",
        "sprite_shader",
        "enemy_west_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_dead1_material",
        "sprite_shader",
        "enemy_dead1_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_dead2_material",
        "sprite_shader",
        "enemy_dead2_texture"
    );

    // Comrade material
    this->resourceManager->addMaterial(
        "comrade_north_material",
        "sprite_shader",
        "comrade_north_texture"
    );
    this->resourceManager->addMaterial(
        "comrade_south_material",
        "sprite_shader",
        "comrade_south_texture"
    );
    this->resourceManager->addMaterial(
        "comrade_east_material",
        "sprite_shader",
        "comrade_east_texture"
    );
    this->resourceManager->addMaterial(
        "comrade_west_material",
        "sprite_shader",
        "comrade_west_texture"
    );
    this->resourceManager->addMaterial(
        "comrade_dead1_material",
        "sprite_shader",
        "comrade_dead1_texture"
    );
    this->resourceManager->addMaterial(
        "comrade_dead2_material",
        "sprite_shader",
        "comrade_dead2_texture"
    );
}