#include "game_assets.hpp"

GameAssets::GameAssets(ResourceManager &resourceManager)
{
    this->resourceManager = &resourceManager;

    // Shaders
    this->resourceManager->addShader(
        "sprite_shader",
        "src/shaders/vertex2.txt",
        "src/shaders/fragment2.txt");
        
    // Meshes
    this->resourceManager->addQuadMesh(
        "sprite_mesh"
    );

    // Textures
    this->resourceManager->addTexture(
        "placeholder_texture",
        "src/assets/textures/placeholder.png"
    );
    this->resourceManager->addTexture(
        "bricks_texture",
        "src/assets/textures/bricks.png"
    );
    this->resourceManager->addTexture(
        "bricks_hit_texture",
        "src/assets/textures/bricks_hit.png"
    );
    this->resourceManager->addTexture(
        "bricks_damaged_texture",
        "src/assets/textures/bricks_damaged.png"
    );
    this->resourceManager->addTexture(
        "bricks_destroyed_texture",
        "src/assets/textures/bricks_destroyed.png"
    );
    this->resourceManager->addTexture(
        "bullet_texture",
        "src/assets/textures/bullet.png"
    );
    this->resourceManager->addTexture(
        "character_hit_texture",
        "src/assets/textures/characters/character_hit.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_texture",
        "src/assets/textures/boards_horizontal.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_hit_texture",
        "src/assets/textures/boards_horizontal_hit.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_damaged_texture",
        "src/assets/textures/boards_horizontal_damaged.png"
    );
    this->resourceManager->addTexture(
        "boards_horizontal_destroyed_texture",
        "src/assets/textures/boards_horizontal_destroyed.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_texture",
        "src/assets/textures/boards_vertical.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_hit_texture",
        "src/assets/textures/boards_vertical_hit.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_damaged_texture",
        "src/assets/textures/boards_vertical_damaged.png"
    );
    this->resourceManager->addTexture(
        "boards_vertical_destroyed_texture",
        "src/assets/textures/boards_vertical_destroyed.png"
    );
    this->resourceManager->addTexture(
        "explosion_texture",
        "src/assets/textures/explosion.png"
    );
    this->resourceManager->addTexture(
        "grenade_on_texture",
        "src/assets/textures/grenade_on.png"
    );
    this->resourceManager->addTexture(
        "grenade_off_texture",
        "src/assets/textures/grenade_off.png"
    );
    this->resourceManager->addTexture(
        "tree_texture",
        "src/assets/textures/tree.png"
    );
    this->resourceManager->addTexture(
        "tree_hit_texture",
        "src/assets/textures/tree_hit.png"
    );
    this->resourceManager->addTexture(
        "tree_destroyed_texture",
        "src/assets/textures/tree_destroyed.png"
    );
    this->resourceManager->addTexture(
        "melee_texture",
        "src/assets/textures/melee.png"
    );

    // Player textures
    this->resourceManager->addTexture(
        "player_north_texture",
        "src/assets/textures/characters/player_north.png"
    );
    this->resourceManager->addTexture(
        "player_south_texture",
        "src/assets/textures/characters/player_south.png"
    );
    this->resourceManager->addTexture(
        "player_east_texture",
        "src/assets/textures/characters/player_east.png"
    );
    this->resourceManager->addTexture(
        "player_west_texture",
        "src/assets/textures/characters/player_west.png"
    );
    this->resourceManager->addTexture(
        "player_dead1_texture",
        "src/assets/textures/characters/player_dead1.png"
    );
    this->resourceManager->addTexture(
        "player_dead2_texture",
        "src/assets/textures/characters/player_dead2.png"
    );

    // Enemy textures
    this->resourceManager->addTexture(
        "enemy_north_texture",
        "src/assets/textures/characters/enemy_north.png"
    );
    this->resourceManager->addTexture(
        "enemy_south_texture",
        "src/assets/textures/characters/enemy_south.png"
    );
    this->resourceManager->addTexture(
        "enemy_east_texture",
        "src/assets/textures/characters/enemy_east.png"
    );
    this->resourceManager->addTexture(
        "enemy_west_texture",
        "src/assets/textures/characters/enemy_west.png"
    );
    this->resourceManager->addTexture(
        "enemy_dead1_texture",
        "src/assets/textures/characters/enemy_dead1.png"
    );
    this->resourceManager->addTexture(
        "enemy_dead2_texture",
        "src/assets/textures/characters/enemy_dead2.png"
    );

    // Materials
    this->resourceManager->addMaterial(
        "placeholder_material",
        "sprite_shader",
        "placeholder_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_material",
        "sprite_shader",
        "bricks_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_hit_material",
        "sprite_shader",
        "bricks_hit_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_damaged_material",
        "sprite_shader",
        "bricks_damaged_texture"
    );
    this->resourceManager->addMaterial(
        "bricks_destroyed_material",
        "sprite_shader",
        "bricks_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "bullet_material",
        "sprite_shader",
        "bullet_texture"
    );
    this->resourceManager->addMaterial(
        "character_hit_material",
        "sprite_shader",
        "character_hit_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_material",
        "sprite_shader",
        "boards_horizontal_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_hit_material",
        "sprite_shader",
        "boards_horizontal_hit_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_damaged_material",
        "sprite_shader",
        "boards_horizontal_damaged_texture"
    );
    this->resourceManager->addMaterial(
        "boards_horizontal_destroyed_material",
        "sprite_shader",
        "boards_horizontal_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_material",
        "sprite_shader",
        "boards_vertical_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_hit_material",
        "sprite_shader",
        "boards_vertical_hit_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_damaged_material",
        "sprite_shader",
        "boards_vertical_damaged_texture"
    );
    this->resourceManager->addMaterial(
        "boards_vertical_destroyed_material",
        "sprite_shader",
        "boards_vertical_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "explosion_material",
        "sprite_shader",
        "explosion_texture"
    );
    this->resourceManager->addMaterial(
        "grenade_on_material",
        "sprite_shader",
        "grenade_on_texture"
    );
    this->resourceManager->addMaterial(
        "grenade_off_material",
        "sprite_shader",
        "grenade_off_texture"
    );
    this->resourceManager->addMaterial(
        "tree_material",
        "sprite_shader",
        "tree_texture"
    );
    this->resourceManager->addMaterial(
        "tree_hit_material",
        "sprite_shader",
        "tree_hit_texture"
    );
    this->resourceManager->addMaterial(
        "tree_destroyed_material",
        "sprite_shader",
        "tree_destroyed_texture"
    );
    this->resourceManager->addMaterial(
        "melee_material",
        "sprite_shader",
        "melee_texture"
    );

    // Player material
    this->resourceManager->addMaterial(
        "player_north_material",
        "sprite_shader",
        "player_north_texture"
    );
    this->resourceManager->addMaterial(
        "player_south_material",
        "sprite_shader",
        "player_south_texture"
    );
    this->resourceManager->addMaterial(
        "player_east_material",
        "sprite_shader",
        "player_east_texture"
    );
    this->resourceManager->addMaterial(
        "player_west_material",
        "sprite_shader",
        "player_west_texture"
    );
    this->resourceManager->addMaterial(
        "player_dead1_material",
        "sprite_shader",
        "player_dead1_texture"
    );
    this->resourceManager->addMaterial(
        "player_dead2_material",
        "sprite_shader",
        "player_dead2_texture"
    );

    // Enemy material
    this->resourceManager->addMaterial(
        "enemy_north_material",
        "sprite_shader",
        "enemy_north_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_south_material",
        "sprite_shader",
        "enemy_south_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_east_material",
        "sprite_shader",
        "enemy_east_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_west_material",
        "sprite_shader",
        "enemy_west_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_dead1_material",
        "sprite_shader",
        "enemy_dead1_texture"
    );
    this->resourceManager->addMaterial(
        "enemy_dead2_material",
        "sprite_shader",
        "enemy_dead2_texture"
    );

    // Colliders
    this->resourceManager->addCollider(
        "character_collider",
        glm::vec2(20, 35)
    );
    this->resourceManager->addCollider(
        "wall",
        glm::vec2(50, 50)
    );
    this->resourceManager->addCollider(
        "boards_horizontal_collider",
        glm::vec2(50, 10)
    );
    this->resourceManager->addCollider(
        "boards_vertical_collider",
        glm::vec2(10, 50)
    );
    this->resourceManager->addCollider(
        "tree_collider",
        glm::vec2(40, 30)
    );

    // Sounds
    this->resourceManager->addSound(
        "gunshot1_sound",
        "src/assets/sounds/gunshot1.wav"
    );
    this->resourceManager->addSound(
        "death_cry1_sound",
        "src/assets/sounds/death_cry1.wav"
    );
    this->resourceManager->addSound(
        "death_cry2_sound",
        "src/assets/sounds/death_cry2.wav"
    );
        this->resourceManager->addSound(
        "death_cry3_sound",
        "src/assets/sounds/death_cry3.wav"
    );
    this->resourceManager->addSound(
        "death_cry4_sound",
        "src/assets/sounds/death_cry4.wav"
    );
    this->resourceManager->addSound(
        "explosion1_sound",
        "src/assets/sounds/explosion1.wav"
    );
    this->resourceManager->addSound(
        "explosion2_sound",
        "src/assets/sounds/explosion2.wav"
    );
    this->resourceManager->addSound(
        "explosion3_sound",
        "src/assets/sounds/explosion3.wav"
    );
}